import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join } from "node:path";

function findAllReports() {
  const reportsDir = "reports/issues";
  const reports = [];
  
  try {
    const issues = readdirSync(reportsDir);
    
    for (const issue of issues) {
      const issuePath = join(reportsDir, issue);
      if (!statSync(issuePath).isDirectory()) continue;
      
      const scans = readdirSync(issuePath);
      for (const scan of scans) {
        const scanPath = join(issuePath, scan);
        if (!statSync(scanPath).isDirectory()) continue;
        
        const reportJsonPath = join(scanPath, "report.json");
        try {
          const reportData = JSON.parse(readFileSync(reportJsonPath, "utf8"));
          reports.push({
            issueNumber: reportData.issueNumber,
            scanTitle: reportData.scanTitle || reportData.issueTitle,
            scannedAt: reportData.scannedAt,
            acceptedCount: reportData.acceptedCount,
            rejectedCount: reportData.rejectedCount,
            alfaTotals: reportData.alfaTotals,
            markdownPath: join(scanPath, "report.md"),
            csvPath: join(scanPath, "report.csv"),
            jsonPath: reportJsonPath
          });
        } catch (err) {
          console.warn(`Could not read ${reportJsonPath}:`, err.message);
        }
      }
    }
  } catch (err) {
    console.warn("Could not read reports directory:", err.message);
  }
  
  // Sort by scanned date descending
  reports.sort((a, b) => new Date(b.scannedAt) - new Date(a.scannedAt));
  
  return reports;
}

function generateIndexHtml(reports) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Alfa Scan Reports</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #24292f;
      background-color: #f6f8fa;
      padding: 2rem;
    }
    
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      padding: 2rem;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);
    }
    
    h1 {
      color: #0969da;
      margin-bottom: 0.5rem;
      font-size: 2rem;
    }
    
    .subtitle {
      color: #57606a;
      margin-bottom: 2rem;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 1rem;
    }
    
    th, td {
      padding: 0.75rem;
      text-align: left;
      border-bottom: 1px solid #d0d7de;
    }
    
    th {
      background-color: #f6f8fa;
      font-weight: 600;
      color: #24292f;
    }
    
    tr:hover {
      background-color: #f6f8fa;
    }
    
    a {
      color: #0969da;
      text-decoration: none;
    }
    
    a:hover {
      text-decoration: underline;
    }
    
    .badge {
      display: inline-block;
      padding: 0.25rem 0.5rem;
      border-radius: 4px;
      font-size: 0.875rem;
      font-weight: 500;
    }
    
    .badge-success {
      background-color: #dafbe1;
      color: #1a7f37;
    }
    
    .badge-danger {
      background-color: #ffebe9;
      color: #cf222e;
    }
    
    .badge-warning {
      background-color: #fff8c5;
      color: #9a6700;
    }
    
    .no-reports {
      text-align: center;
      padding: 3rem;
      color: #57606a;
    }
    
    .date {
      color: #57606a;
      font-size: 0.875rem;
    }
    
    .links {
      display: flex;
      gap: 1rem;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Alfa Scan Reports</h1>
    <p class="subtitle">Accessibility scan reports generated by GitHub Actions</p>
    
    ${reports.length === 0 ? `
    <div class="no-reports">
      <p>No scan reports available yet.</p>
    </div>
    ` : `
    <table>
      <thead>
        <tr>
          <th>Issue</th>
          <th>Scan Title</th>
          <th>Scanned At</th>
          <th>URLs</th>
          <th>Results</th>
          <th>Reports</th>
        </tr>
      </thead>
      <tbody>
        ${reports.map(report => `
        <tr>
          <td><a href="https://github.com/${process.env.GITHUB_REPOSITORY || 'mgifford/alfa-scan'}/issues/${report.issueNumber}">#${report.issueNumber}</a></td>
          <td>${escapeHtml(report.scanTitle)}</td>
          <td class="date">${new Date(report.scannedAt).toLocaleString()}</td>
          <td>${report.acceptedCount} accepted${report.rejectedCount > 0 ? `, ${report.rejectedCount} rejected` : ''}</td>
          <td>
            <span class="badge badge-success">${report.alfaTotals.passed} passed</span>
            ${report.alfaTotals.failed > 0 ? `<span class="badge badge-danger">${report.alfaTotals.failed} failed</span>` : ''}
            ${report.alfaTotals.cantTell > 0 ? `<span class="badge badge-warning">${report.alfaTotals.cantTell} can't tell</span>` : ''}
          </td>
          <td class="links">
            <a href="${report.markdownPath}">Markdown</a>
            <a href="${report.csvPath}">CSV</a>
            <a href="${report.jsonPath}">JSON</a>
          </td>
        </tr>
        `).join('')}
      </tbody>
    </table>
    `}
  </div>
</body>
</html>`;
  
  return html;
}

function escapeHtml(text) {
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return String(text).replace(/[&<>"']/g, m => map[m]);
}

const reports = findAllReports();
const html = generateIndexHtml(reports);
writeFileSync("index.html", html, "utf8");
console.log(`Generated index.html with ${reports.length} reports`);
