/**
 * AI-powered source-code accessibility review.
 *
 * Reads the project's own HTML and JS source files and uses the GitHub Models
 * API to review them for WCAG 2.2 accessibility issues. This is inspired by
 * the GitHubNext daily-accessibility-review workflow and complements the
 * existing runtime axe-core scanning in scan-github-pages.yml.
 *
 * Design principles:
 * - Source-code review catches structural/semantic issues that runtime scanners
 *   may miss (e.g. ARIA misuse in templates, missing landmarks, CSS colour
 *   token naming concerns)
 * - Gracefully degrades when the GitHub Models API is unavailable
 * - stdout: JSON output only (follows project convention)
 * - stderr: all progress and diagnostic messages
 *
 * Usage (CLI):
 *   node scanner/review-source.mjs [file1 file2 ...]
 *
 *   Defaults to: index.html reports.html trends.html submit.js
 *
 * Environment variables:
 *   GITHUB_TOKEN   Required. GitHub token with models:read scope.
 *   MODEL          Optional. Model ID override (default: gpt-4o-mini).
 *
 * Stdout:
 *   JSON object:
 *   {
 *     hasFindings: boolean,    // true if the review identified any issues
 *     reviewText: string,      // Markdown review suitable for a GitHub issue
 *     filesReviewed: string[], // paths that were successfully read
 *     model: string,           // model used
 *     skipped: boolean         // true if API was unavailable / no token
 *   }
 */

import { readFileSync } from "node:fs";

const GITHUB_MODELS_ENDPOINT =
  "https://models.inference.ai.azure.com/chat/completions";

const DEFAULT_MODEL = "gpt-4o-mini";

/**
 * Maximum characters read from each file.
 * Keeps individual file content within context window limits.
 */
const MAX_CHARS_PER_FILE = 8000;

/**
 * Default set of source files to review (relative to repo root).
 */
const DEFAULT_FILES = ["index.html", "reports.html", "trends.html", "submit.js"];

/**
 * AI disclaimer appended to all generated output.
 */
export const REVIEW_DISCLAIMER =
  "⚠️ **AI Disclaimer**: This WCAG 2.2 review was generated by an AI model " +
  "(GitHub Models / gpt-4o-mini) and may contain errors or omissions. " +
  "Always verify findings manually before implementing fixes. " +
  "This is a source-code review and complements (does not replace) " +
  "runtime accessibility scanning with axe-core.";

/**
 * Build the system prompt for the WCAG 2.2 source-code review.
 * @returns {string}
 */
function buildSystemPrompt() {
  return [
    "You are an expert web accessibility engineer specialising in WCAG 2.2 compliance.",
    "Review the provided HTML and JavaScript source code for accessibility issues.",
    "For each issue found, structure your response as follows:",
    "",
    "1. **Issue title** — one line summary",
    "2. **File and code snippet** — the relevant lines",
    "3. **WCAG criterion** — e.g. '1.3.1 Info and Relationships (Level A)'",
    "4. **Impact** — who is affected and how severely",
    "5. **Recommendation** — a concrete, actionable fix",
    "",
    "Focus on real, verifiable issues. Avoid speculative findings.",
    "Group issues by WCAG principle (Perceivable, Operable, Understandable, Robust).",
    "End with a brief summary: total issue count, most critical issue, and overall assessment.",
    "Format your response as valid Markdown suitable for a GitHub issue body.",
    "If no accessibility issues are found, say so clearly.",
  ].join("\n");
}

/**
 * Read a source file and truncate to MAX_CHARS_PER_FILE.
 *
 * @param {string} filePath
 * @returns {{ path: string, content: string, truncated: boolean }|null}
 */
function readSourceFile(filePath) {
  try {
    const raw = readFileSync(filePath, "utf8");
    const truncated = raw.length > MAX_CHARS_PER_FILE;
    const content = truncated
      ? raw.slice(0, MAX_CHARS_PER_FILE) + "\n... [content truncated at 8000 characters]"
      : raw;
    console.error(
      `[review-source] Read ${filePath} (${raw.length} chars${truncated ? ", truncated" : ""})`
    );
    return { path: filePath, content, truncated };
  } catch (err) {
    console.error(
      `[review-source] Could not read ${filePath}: ${err.message}`
    );
    return null;
  }
}

/**
 * Call the GitHub Models API to review source files for WCAG 2.2 issues.
 *
 * @param {Array<{path: string, content: string}>} files
 * @param {string} token
 * @param {string} model
 * @returns {Promise<string>} Markdown review text
 */
async function callReviewApi(files, token, model) {
  const userContent =
    "Review the following source files for WCAG 2.2 accessibility issues " +
    "(target: Level AA compliance):\n\n" +
    files
      .map(({ path, content }) => `### File: \`${path}\`\n\`\`\`\n${content}\n\`\`\``)
      .join("\n\n");

  const body = JSON.stringify({
    model,
    messages: [
      { role: "system", content: buildSystemPrompt() },
      { role: "user", content: userContent },
    ],
    temperature: 0.2,
    max_tokens: 2048,
  });

  const response = await fetch(GITHUB_MODELS_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body,
    signal: AbortSignal.timeout(60_000),
  });

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(
      `GitHub Models API returned ${response.status}: ${text.slice(0, 200)}`
    );
  }

  const data = await response.json();
  return data?.choices?.[0]?.message?.content ?? "";
}

/**
 * Wrap the raw review text in a formatted GitHub issue body.
 *
 * @param {string} reviewText
 * @param {string[]} filesReviewed
 * @param {string} model
 * @returns {string}
 */
export function formatReviewIssueBody(reviewText, filesReviewed, model) {
  const lines = [
    "## 🔍 AI Accessibility Review (WCAG 2.2)",
    "",
    "> **Source**: Automated review using GitHub Models API — inspired by",
    "> [GitHubNext daily-accessibility-review](https://github.com/githubnext/agentics/blob/main/docs/daily-accessibility-review.md)",
    `> **Scope**: WCAG 2.2 Level AA source-code review of \`${filesReviewed.join("`, `")}\``,
    "> **Triggered**: Manually via workflow_dispatch",
    "",
    `> ${REVIEW_DISCLAIMER}`,
    "",
    "---",
    "",
    reviewText,
    "",
    "---",
    "",
    `*Review generated: ${new Date().toISOString()}*`,
    `*Model: ${model} — Files reviewed: ${filesReviewed.join(", ")}*`,
  ];

  return lines.join("\n");
}

/**
 * Determine whether the review text contains accessibility findings.
 *
 * A "finding" is any issue description. We treat the review as having
 * findings unless the text explicitly states that no issues were found.
 *
 * @param {string} reviewText
 * @returns {boolean}
 */
export function detectHasFindings(reviewText) {
  if (!reviewText || reviewText.trim().length === 0) return false;
  const lower = reviewText.toLowerCase();
  const noIssuesPhrases = [
    "no accessibility issues",
    "no issues found",
    "no wcag violations",
    "no violations found",
    "fully accessible",
    "no issues were found",
  ];
  return !noIssuesPhrases.some((phrase) => lower.includes(phrase));
}

/**
 * Main entry point. Resolves the list of files to review, calls the API,
 * and writes structured JSON to stdout.
 *
 * @param {string[]} filePaths
 * @param {{ token?: string, model?: string }} options
 * @returns {Promise<void>}
 */
export async function reviewSource(
  filePaths = DEFAULT_FILES,
  { token, model = DEFAULT_MODEL } = {}
) {
  if (!token) {
    console.error(
      "[review-source] GITHUB_TOKEN not set — skipping AI review"
    );
    console.log(
      JSON.stringify({
        hasFindings: false,
        reviewText: "",
        filesReviewed: [],
        model,
        skipped: true,
        reason: "GITHUB_TOKEN not available",
      })
    );
    return;
  }

  const loadedFiles = filePaths
    .map(readSourceFile)
    .filter((f) => f !== null);

  if (loadedFiles.length === 0) {
    console.error("[review-source] No files could be read");
    console.log(
      JSON.stringify({
        hasFindings: false,
        reviewText: "",
        filesReviewed: [],
        model,
        skipped: true,
        reason: "No files could be read",
      })
    );
    return;
  }

  const filesReviewed = loadedFiles.map((f) => f.path);
  console.error(
    `[review-source] Reviewing ${filesReviewed.length} file(s) with ${model}...`
  );

  let reviewText;
  try {
    reviewText = await callReviewApi(loadedFiles, token, model);
    console.error(
      `[review-source] Received ${reviewText.length} chars from API`
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[review-source] API call failed: ${msg}`);
    console.log(
      JSON.stringify({
        hasFindings: false,
        reviewText: "",
        filesReviewed,
        model,
        skipped: true,
        reason: `API call failed: ${msg}`,
      })
    );
    return;
  }

  const hasFindings = detectHasFindings(reviewText);
  const issueBody = formatReviewIssueBody(reviewText, filesReviewed, model);

  console.log(
    JSON.stringify({
      hasFindings,
      reviewText,
      issueBody,
      filesReviewed,
      model,
      skipped: false,
    })
  );
}

// Run as a CLI script when executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  const rawArgs = process.argv.slice(2);
  // Support both: multiple args ("file1.html" "file2.html") and a single
  // space-separated arg ("file1.html file2.html") produced by shell quoting.
  const filePaths =
    rawArgs.length === 0
      ? DEFAULT_FILES
      : rawArgs.length === 1 && rawArgs[0].includes(" ")
        ? rawArgs[0].split(/\s+/).filter(Boolean)
        : rawArgs;

  reviewSource(filePaths, {
    token: process.env.GITHUB_TOKEN,
    model: process.env.MODEL || DEFAULT_MODEL,
  }).catch((err) => {
    console.error(`[review-source] Fatal error: ${err.message}`);
    process.exit(1);
  });
}
